### ISSUE TITLE
[INVALID] [BUG] Hardcoded relative path for node_modules

### ISSUE THREAD

**Issue by ghost** [SillyTavern/SillyTavern#1868]
### Environment

Self-Hosted (Bare Metal)

### System

debian 12 64bit

### Version

1.11.5

### Describe the problem

It seams that the code now references the node_modules folder directly. So the folder can't be moved anymore with NODE_PATH. It seams it was working fine in 1.11.4

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
The only thing that refers to node_modules directly is a [post-install](https://github.com/SillyTavern/SillyTavern/blob/release/post-install.js#L147) script, it was added 5 months ago.

You can review the latest release merge to see that nothing referencing node_modules was added: https://github.com/SillyTavern/SillyTavern/pull/1866

**Comment by ghost** [comment]
try moving node_modules with NODE_PATH

**Comment by ghost** [comment]
i get
```
node:internal/modules/cjs/loader:1137
  throw err;
  ^

Error: Cannot find module 'open'
```

**Comment by Cohee1207** [comment]
You get it how exactly? Can I get the exact steps to reproduce?

**Comment by Cohee1207** [comment]
I did some digging through the documentation. NODE_PATH can be [considered legacy](https://nodejs.org/api/modules.html#loading-from-the-global-folders), and [can't load ES Modules](https://nodejs.org/api/esm.html#esm_no_node_path) which are slowly becoming a new standard for Node programs as it is the [official format](https://tc39.es/ecma262/#sec-modules) for JavaScript code and more and more libraries are gradually migrating to ESM.

> It is strongly encouraged to place dependencies in the local node_modules folder. These will be loaded faster, and more reliably.

**Comment by ghost** [comment]
yep.... then, there's no bug
